version: "3"

services:
    flask_d3_app_dev:
        image: flask_d3_app_dev:1.00
        container_name: flask_d3_app_dev
        restart: unless-stopped
        command: manage.py runserver --host=0.0.0.0 --port=3000
        build:
            context: ../
            dockerfile: .dev-tools/Dockerfile.test
        ports:
            - "3000:3000"
        volumes:
            - ..:/usr/app
        stdin_open: true